;;
; Copyright Jacques Deschênes 2019 
; This file is part of PABasic 
;
;     PABasic is free software: you can redistribute it and/or modify
;     it under the terms of the GNU General Public License as published by
;     the Free Software Foundation, either version 3 of the License, or
;     (at your option) any later version.
;
;     PABasic is distributed in the hope that it will be useful,
;     but WITHOUT ANY WARRANTY; without even the implied warranty of
;     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;     GNU General Public License for more details.
;
;     You should have received a copy of the GNU General Public License
;     along with PABasic.  If not, see <http://www.gnu.org/licenses/>.
;;
;--------------------------------------

    BYE=0
    PUTC=BYE+1
    GETC=PUTC+1
    PUTS=GETC+1
    DELETE=PUTS+1
    SPACES=DELETE+1
    LIT=SPACES+1
    LITC=LIT+1
    PLUS=LITC+1
    MINUS=PLUS+1
    SLASH=MINUS+1
    MOD=SLASH+1
    STAR=MOD+1

